#!/bin/bash

if echo $1 | egrep "\-c" >&/dev/null
then
	if echo $USER | egrep -v "root" >&/dev/null
	then exit 1
	else exit 0 
	fi
fi
if echo $1 | egrep "\-u" >&/dev/null
then 
	if groups $USER | egrep -v "sudo" >&/dev/null
	then exit 1
	else exit 0
	fi
fi
echo "Befehl nicht angegeben
verwende -c um zu testen ob du den Befehl als root (mit sudo) ausführst.
verwende -u um zu testen ob du root-Rechte hast."
exit 2
